name: app-backend

networks:
  shared-network:
    external: true

services:
  app:
    container_name: app-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev # Specify the environment here
    environment:
      CONFIG_ENV: dev
      LOG_LEVEL: debug
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./.env:/app/.env
    networks:
      - shared-network
    
